
cloudinary.cloud-name=dtajgg3xo
cloudinary.api-key=414963236997351
cloudinary.api-secret=x-IQGCUBMex-RsFHt7ryQ7FtTvU
spring.datasource.url=jdbc:postgresql://localhost:2310/mriya_db
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect