spring.datasource.url=jdbc:postgresql://localhost:5432/mriya_db
spring.datasource.username=Taras_Kushmyruk
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect